spring.application.name=my-market-app

# Database configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/marketdb
spring.datasource.username=market_user
spring.datasource.password=mysecretpassword
