spring.application.name=my-market-app

# Database configuration
spring.r2dbc.url=r2dbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
spring.r2dbc.username=${POSTGRES_USER}
spring.r2dbc.password=${POSTGRES_PASSWORD}

# Liquibase configuration
spring.liquibase.url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
spring.liquibase.user=${POSTGRES_USER}
spring.liquibase.password=${POSTGRES_PASSWORD}
spring.liquibase.change-log=classpath:/db/changelog/db.changelog-master.xml

# Catalog loader configuration
app.catalog.csv-path=data/products.csv
app.catalog.images-path=data/images
app.catalog.load-on-startup=true
