# Database dev config
spring.r2dbc.url=r2dbc:postgresql://localhost:5432/marketdb
spring.r2dbc.username=postgres
spring.r2dbc.password=postgres

# Liquibase dev config
spring.liquibase.url=jdbc:postgresql://localhost:5432/marketdb
spring.liquibase.user=postgres
spring.liquibase.password=postgres
