CREATE TABLE IF NOT EXISTS products (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title       VARCHAR(255)  NOT NULL,
    description VARCHAR(2000),
    img_path    VARCHAR(255),
    price       BIGINT        NOT NULL,
    external_id VARCHAR(255),
    CONSTRAINT uk_products_external_id UNIQUE (external_id)
);

CREATE TABLE IF NOT EXISTS orders (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE
);

CREATE TABLE IF NOT EXISTS order_items (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id   BIGINT       NOT NULL,
    product_id BIGINT       NOT NULL,
    title      VARCHAR(255) NOT NULL,
    price      BIGINT       NOT NULL,
    quantity   INT          NOT NULL,
    CONSTRAINT fk_order_items_order FOREIGN KEY (order_id) REFERENCES orders (id)
);
